[package]
name = "xv6-rust-project"
version = "0.1.0"
authors = ["BigBillZhao <11811715@mail.sustech.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
